name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Display Java version and JAVA_HOME
        run: |
          java -version
          echo $JAVA_HOME

      - name: Build with Maven
        run: ./mvnw clean install --batch-mode --no-transfer-progress

      - name: Run Tests and Generate Code Coverage
        run: ./mvnw clean test jacoco:report --batch-mode --no-transfer-progress

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: 7ffaabba-b312-4074-92e5-05c55bfbe56b

