name: Build

on: push

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Java
              uses: actions/setup-java@v2
              with:
                  distribution: 'temurin'
                  java-version: '17'

            - name: Cache Maven dependencies
              uses: actions/cache@v2
              with:
                  path: ~/.m2/repository
                  key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                  restore-keys: |
                      ${{ runner.os }}-maven-

            - name: Display Java version and JAVA_HOME
              run: |
                  java -version
                  echo $JAVA_HOME

            - name: Build with Maven
              run: ./mvnw install

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v1

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v3
